### ISSUE TITLE
Allow selection of additional identifiers for C. elegans

### ISSUE THREAD

**Issue by knightjdr** [knightjdr/gene-info#11]
### Wormbase IDs

- e.g. WBGene00000536
- always prefixed with WBGene

### Coding sequence (CDS)

- e.g. ZC395.2 and Y46C8AL.9a:wp261
- possible regex: `\w+\.\w+(?::wp\d+)?`
- this is referenced as ORF in UniProt
- can currently query by this by turning off autodetect and setting the query type to `ORF`
- is not currently autodetected

**Comment by JonathanEwbank** [comment]
WBGeneIDs are the prime and unique gene identifiers. A single WBGeneID is associated with just one gene sequence name, irrespective of the number of isoforms (ZC395.2, ZK637.8). If there is only one isoform, the CDS sequence name matches the gene sequence name (ZC395.2), and if there are different splice isoforms there are several CDS sequence names (ZK637.8a - ZK637.8f). A subset of WBGeneIDs are also associated with a "common gene name" (unc-32).

The correspondence tables for these are at 
ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/annotation/
in the file c_elegans.PRJNA13758.WSNNN.geneIDs.txt.gz where NNN is the number of the current release.

Detection of WBGeneIDs, common gene names and the single gene sequence name would cover >95% of all cases and already be very useful.


Further details of naming conventions are at https://wormbase.org/about/userguide/nomenclature. Clarification can be requested from https://wormbase.org/resources/person/WBPerson1983

IDs for protein coding sequences that include the WormPep release (Y46C8AL.9a:wp261) are currently virtually unused; their autodetection should not be a priority.

**Comment by knightjdr** [comment]
We're already parsing Wormbase IDs for linking to that site and gene sequence names (as ORFS).

I'll just need to enable selection and autodetection for these.

We aren't currently parsing isoforms, although I can add that.

We're in the midst of a few changes so this probably won't be available for a month or so.

**Comment by JonathanEwbank** [comment]
Having the common gene names (https://www.ncbi.nlm.nih.gov/pubmed/31532389) would be a valuable aid too.

Isoform autodetection is less of an issue.

**Comment by knightjdr** [comment]
Sorry, what do you mean by common gene names and can you give me a specific example? I was thinking we already support this. We have official symbol and synonyms, but you mean something else it sounds like.

**Comment by JonathanEwbank** [comment]
Sorry, my mistake. It is a result of having changed the browser preferences to capture hyphenated gene names; it’s the issue that you identified: if a comma or other punctuation follows the gene name then the double click extends the selection to include the trailing punctuation mark. As you explained elsewhere, GIX already offers a solution using the “drag” option. Switching to that capture method, it works a treat.
