### ISSUE TITLE
Support for prokaryotic species.

### ISSUE THREAD

**Issue by Biafra1987** [knightjdr/gene-info#13]
It would be excellent to extend the use of the extension to most common bacterial species. Inclusion of E.coli and Salmonella would certainly broaden the potential userbase of the tool.

**Comment by knightjdr** [comment]
Adding species is simple enough to do although I'm not overly familiar with prokaryotic taxonomy.

It looks like we need to pick specific strains/subspecies our else there will be a great deal of redundancy. For example, searching for the gene `tir` and <i>Escherichia coli</i> yields multiple reviewed entries at UniProt for the different strains.

For E.coli, should it be strain K12 (taxon ID 83333) to use? If I search for `organism:"Escherichia coli (strain K12) [83333]" AND reviewed:yes` at UniProt it yields a total of 4,518 results.

The most prevalent Salmonella subspecies in UniProt is Salmonella typhimurium (strain LT2 / SGSC1412 / ATCC 700720, taxon ID 99287). Searching for `organism:"Salmonella typhimurium [99287]" AND reviewed:yes` yields 1,799 entries.

**Comment by Biafra1987** [comment]
Indeed, K12 is arguably the most commonly used background strain and certainly seems like the best annotated/studied (therefore, it covers most confidently annotated genes). Similarly, for Salmonella SL1344 (tax 216597) is a commonly used background for most infection-relevant work.

**Comment by knightjdr** [comment]
Okay, thanks.

Unfortunately, as it looks like you've noticed, SL1344 only has 36 reviewed UniProt entries. We use reviewed UniProt entries as the starting point for entries in our database and add additional information from other sources. So it looks like LT2 would be the better choice.

Any other major prokaryotic species you would suggest?

**Comment by Biafra1987** [comment]
I would be going outside of my area of expertise but commonly studied bacteria with large fraction of verified entries include Bacillus subtilis and Listeria monocytogenes. 
There are also a few organisms studied in our department by people interested in using GIX in their day to day- Ralstonia solanacearum and Citrobacter rodentium (not sure how much redundancy these would introduce). Clearly manual verification is not as developed for bacteria given the huge variety of organisms and strains.

**Comment by knightjdr** [comment]
We'll take a look and do what we can. This can probably be available in our March 15th update.

**Comment by Biafra1987** [comment]
Thank you so much! Love the paper and the tool. Good luck!

**Comment by knightjdr** [comment]
We've added <i>Escherichia coli</i> (strain K12) and <i>Salmonella Typhimurium</i> (strain LT2). Unfortunately, the other species you mentioned don't have enough reviewed entries.

This update is currently live in Firefox (v1.4.1) and is pending review with Chrome (usually takes 2-3 business days).
