### ISSUE TITLE
Compatibility with HTML files

### ISSUE THREAD

**Issue by NMikolajewicz** [knightjdr/gene-info#14]
I routinely generate HTML report that have tables embedded with in them. I found that GIX works flawlessly when I use Firefox to open the HTML report, however, it fails when the report is opened in Chrome citing that 'Either your browser does not allow queries on this page, or you may need to hit refresh if you've just installed the extension.' Is it possible to extend HTML support to Chrome?

Thank you,
NM

**Comment by knightjdr** [comment]
If I understand correctly you have a local HTML file you are opening in the browser. Firefox allows extensions to load on pages beginning with file:/// by default but Chrome does not without the user giving explicit permission.

To do this, right-click on the extension and click "Manage extensions". Toggle the option that says "Allow access to file URLs". This should fix it.

**Comment by NMikolajewicz** [comment]
Toggling the 'Allow access to file URLs' worked. Thanks for you fast response!
