### ISSUE TITLE
Link to locally held raw DNA file like SNPTips used to

### ISSUE THREAD

**Issue by allsonic** [knightjdr/gene-info#16]
It would be fantastic if when double clicking it was possible for the window to also contain information regarding your genotype pulled form a locally held raw data file. Much like what an old Firefox plugin did called SNPTips used to do. This would make it quicker and easier for people interested in genetics to check and compare their genotypes.

SNPTips on GitHub - https://github.com/belvario/snptips
SNPTips example video - https://www.youtube.com/watch?v=4d6Vs3PNE_g

**Comment by knightjdr** [comment]
Unfortunately this is a bit too far outside our intended scope for the amount of work involved. I think your best bet would be to fork snptips and release a new version yourself.
