### ISSUE TITLE
Missing option to toggle "Ctrl+double click" in 1.8.3

### ISSUE THREAD

**Issue by cosminribo** [knightjdr/gene-info#18]
Hi and thank you for this wonderful extension. I cannot find the option allowing the switch to Ctrl+double click behavior. I tried to use the 1.8.3 version of the extension on both Chrome (116) and Firefox (117). Attaching a screenshot showing the available options for the extension. Thank you.
![extension_prefs](https://github.com/knightjdr/gene-info/assets/5047356/7351d5bb-c850-4855-80af-b25bf8b308b0)

**Comment by cosminribo** [comment]
I'm sorry - I understood now that the preferences of the addon can be accessed by clicking on its icon in the toolbar. Everything is fine.

**Comment by knightjdr** [comment]
Sorry for the slow response, but glad to hear you found these options.
