### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by Jansenht** [knightjdr/gene-info#19]
App is not launching upon selection

The following error is seen:

An error occured. Please use our [issue tracker](https://github.com/knightjdr/gene-info/issues) to report bugs.

**Comment by knightjdr** [comment]
There is currently an outage with our cloud provider and we are reliant on them to fix the underlying hardware issue. No eta for a fix yet I'm afraid.

**Comment by XIANZHE-LI** [comment]
> There is currently an outage with our cloud provider and we are reliant on them to fix the underlying hardware issue. No eta for a fix yet I'm afraid.

I still can't use it, so when will I be able to use it

**Comment by knightjdr** [comment]
It is online again. Apologies for the outage, but our cloud provider had a major issue.
