### ISSUE TITLE
Sorting Interactors List

### ISSUE THREAD

**Issue by PeterDeWeirdt** [knightjdr/gene-info#4]
Really nice work with this tool. Allowing users to sort the interactors list, either by BioGRID or IntAct evidence, could help to pick out top hits from the list.

**Comment by knightjdr** [comment]
Thanks Peter. Makes sense and shouldn't be tough to add.

**Comment by PeterDeWeirdt** [comment]
Great! Thank you

**Comment by knightjdr** [comment]
I'll leave this open until the feature is added. It may take a couple weeks for me to get to it, then a week of testing and roughly a week for Google to review the update.  So ~ a month or so.

**Comment by knightjdr** [comment]
This has been added efc483979f7eef9b70702f9f6391cf6d459facdc

We won't deploy any changes until we get reviewer comments back, but hopefully it won't be long.

**Comment by knightjdr** [comment]
This is now live.
