### ISSUE TITLE
PMID: link

### ISSUE THREAD

**Issue by ValWood** [knightjdr/gene-info#7]
** provide a pop up when PMIDs are selected to  organism-specific gene pages**

so for example the PomBase suggestion would be:
https://www.pombase.org/reference/PMID:30355493

**Comment by knightjdr** [comment]
Sorry, I'm not sure what you're asking. Can you provide some more detail?

**Comment by ValWood** [comment]
So a mouse over of a PMID (in a paper  for example)

PubMed  -> https://www.ncbi.nlm.nih.gov/pubmed?holding=pombase&term=28539404
Pombase -> https://www.pombase.org/reference/PMID:29699848 (other mODs have equivalent pages)

(It would require a new query type, "Citation" or similar)

**Comment by knightjdr** [comment]
Matching publications is quite different from what we are currently doing so I don’t see this being added in the foreseeable future.
